config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :blocked_addresses
    resources :calendars
    resources :championships
    resources :clubs
    resources :club_admin_roles
    resources :days
    resources :duty_tasks
    resources :enrolled_team_championships
    resources :groups
    resources :locations
    resources :matches
    resources :match_availabilities
    resources :match_selections
    resources :participations
    resources :seasons
    resources :sections
    resources :section_user_invitations
    resources :selections
    resources :teams
    resources :trainings
    resources :training_invitations
    resources :training_presences
    resources :users

    root to: 'users#index'
  end
  resources :days

  resources :championships

  resources :sections, only: %i[show] do
    resources :duty_tasks do
      collection do
        get 'leaderboard'
      end
    end
    resources :section_user_invitations, path: 'user_invitations', only: %i[new show create index]
    resources :trainings do
      resources :users, only: [] do
        get 'training_presence' => 'training_presences#show'
      end
      member do
        get 'presence_validation'
        post 'invitations'
        post 'cancellation'
        post 'repeat'
        delete 'uncancel'
      end
    end
    resources :absences, only: %i[index]
    resources :users, path: 'members' do
      resources :trainings, only: [] do
        resources :training_presences, only: %i[create show]
        delete 'training_presences' => 'training_presences#destroy'
        post 'confirm_presence' => 'training_presences#confirm_presence'
      end
      resources :absences, only: %i[index create edit update destroy new]
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end

    resources :participations_renewal, only: %i[index create]

    resources :groups do
      post 'users' => 'groups#add_users', as: 'add_users'
      resources :users, only: [:destroy]
    end
    resources :matches do
      member do
        post :selection
        resources :selections, only: [:destroy]
        post 'invitations'
      end
    end
    resources :championships do
      member do
        get :merge_calendar_form
        post :merge_calendar
      end
      resources :matches
      resources :enrolled_team_championships, only: %i[index create destroy]
      resources :burns, only: %i[index create destroy]
    end
    resources :days, only: %i[create update] do
      resources :selections, only: [:index]
    end
    resources :calendars, only: %i[index create edit update]
    resources :days, only: [:create]
    resources :locations, only: [:create]
    resources :teams, only: %i[create show destroy new]
    resources :channels do
      resources :messages, only: %i[create destroy]
    end
    resources :events, only: %i[index]

    patch 'player_ffhb_association'
    delete 'dissociate_player'
  end

  resources :club_admin_roles, only: %i[index show]

  resources :teams, only: %i[index show]

  resources :clubs, only: %i[index show] do
    resources :sections, only: %i[index new create destroy edit update]
  end

  devise_for :users, except: %i[show]

  resources :users, only: %i[show edit update] do
    member do
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end
  end

  resources :messages, only: [] do
    collection do
      post 'mark_as_read'
    end
  end

  resources :webpush_subscriptions, only: [:create], constraints: { format: :json }

  authenticate :user, ->(u) { u.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  root to: 'visitors#index'

  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  get '.well-known/acme-challenge/4k3hP8fSRgCKf0inS8qYK9LYs8sU10ZMfSiYs8-Mcxg' => 'visitors#letsencrypt'
  get '.well-known/acme-challenge/DNyCHVFZJQpss-fIqj5vX317OwOjUfwRklgsSJMAJXo-Mcxg' => 'visitors#letsencrypt'

  get '.stimulus', to: 'visitors#stimulus'
end
# rubocop:enable Metrics/BlockLength

app/models/training.rb
# frozen_string_literal: true

class Training < ApplicationRecord
  belongs_to :location, optional: true

  has_many :section_trainings, dependent: :destroy
  has_many :sections, through: :section_trainings
  has_many :group_trainings, dependent: :destroy
  has_many :groups, through: :group_trainings

  has_many :invitations, class_name: 'TrainingInvitation', dependent: :destroy
  has_many :training_presences, inverse_of: :training, dependent: :destroy
  has_many :present_players, lambda {
                               where(training_presences: { is_present: true })
                             }, through: :training_presences, source: :user
  has_many :users, through: :groups

  validates :start_datetime, presence: true

  scope :of_section, ->(section) { joins(:sections).where(sections: { id: section.id }) }
  scope :not_cancelled, -> { where.not('cancelled') }
  scope :with_start_between, lambda { |start_period, end_period|
                               where(start_datetime: start_period..end_period)
                             }
  scope :with_start_on, ->(days) { where('DATE(start_datetime) in (?)', days) }

  default_scope { order :start_datetime, :location_id }

  paginates_per 10

  alias_attribute :calculated_start_datetime, :start_datetime

  DUTY_PER_TRAINING = 4

  def send_invitations!
    invitations << TrainingInvitation.new
  end

  def presents
    training_presences.includes(:user).where(is_present: true).map(&:user)
  end

  def nb_presents
    presents.count
  end

  def not_presents
    training_presences.includes(:user).where(is_present: false).map(&:user)
  end

  def nb_not_presents
    not_presents.count
  end

  def nb_presence_not_set
    presence_not_set.size
  end

  def presence_not_set
    users - presents - not_presents
  end

  def group_names
    groups.order(:name).map(&:name).join(', ')
  end

  def users
    User.joins(:groups).where(groups: { id: group_ids })
  end

  def repeat_next_week!
    Training.create!(start_datetime: start_datetime + 1.week,
                     end_datetime: end_datetime + 1.week,
                     sections:, groups:, location:, max_capacity:)
  end

  def repeat_until!(end_date)
    training = self
    end_date -= 1.week
    training = training.repeat_next_week! while training.start_datetime < end_date
  end

  def cancel!(reason: 'Raison inconnue')
    self.cancelled = true
    self.cancel_reason = reason
    save!
  end

  def uncancel!
    self.cancelled = false
    self.cancel_reason = nil
    save!
  end

  def next_duties(limit)
    current_season_start = Season.current.start_date
    current_season_end = Season.current.end_date

    present_players
      .where("email NOT LIKE '%@example.com'")
      .joins(<<-SQL.squish)
        LEFT OUTER JOIN duty_tasks
        ON duty_tasks.user_id = users.id
        AND duty_tasks.realised_at BETWEEN '#{current_season_start}' AND '#{current_season_end}'
        AND duty_tasks.club_id IN (#{sections.map(&:club_id).join(',')})
      SQL
      .distinct
      .select(<<-SQL.squish)
        users.*,
        MAX(duty_tasks.realised_at) AS last_duty_date,
        COALESCE(SUM(duty_tasks.weight), -1) AS sum_duty_tasks_weight
      SQL
      .group('users.id')
      .order(:sum_duty_tasks_weight, :last_duty_date, :authentication_token)
      .limit(limit)
  end

  def name
    "#{start_datetime.strftime('%d %b')} - #{location&.name}"
  end

  def self.send_presence_mail_for_next_week(date = DateTime.now)
    User.where("email not like '%@example.com'").active_this_season.each do |user|
      next_week_trainings = user.next_week_trainings(date:)
      unless next_week_trainings.empty?
        UserMailer.send_training_invitation(next_week_trainings.to_a,
                                            user).deliver_later
      end
    end
  end

  def self.send_tig_mail_for_next_training(day_range = 2)
    tomorrow = Date.tomorrow
    trainings =
      Training
      .where(cancelled: [false, nil])
      .where('start_datetime between ? and ?', tomorrow.to_datetime, (tomorrow + day_range.days).to_datetime)
      .order(:start_datetime)

    trainings.each do |training|
      next_duties = training.next_duties(DUTY_PER_TRAINING)
      next if next_duties.blank?
      next if training.sections.map(&:id).uniq == [1]

      # if training is in section 1, than add pechou as last next duty
      cc = training.sections.map(&:id).include?(1) ? User.find(49) : nil

      UserMailer.send_tig_mail_for_training(training, next_duties.to_a, cc).deliver_later
    end
  end

  def max_capacity_reached?
    return false if max_capacity.nil?

    present_players.count >= max_capacity
  end
end

app/controllers/admin/trainings_controller.rb
# frozen_string_literal: true

module Admin
  class TrainingsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/trainings_controller.rb
# frozen_string_literal: true

class TrainingsController < ApplicationController
  before_action :set_current_training
  include PrefetchTrainingData

  def index
    section_trainings = current_section.trainings.eager_load(:location, :groups).where('start_datetime > ?',
                                                                                       Season.current.start_date)

    if params[:page].blank?
      training_before_beginning_of_week =
        section_trainings.where(start_datetime: ...Time.zone.now.beginning_of_week)
      page = (training_before_beginning_of_week.count / 10) + 1
      redirect_to section_trainings_path(current_section, page:)
      return
    end

    @trainings = section_trainings.page(params[:page])
    add_training_prefetch_data(@trainings)
  end

  def show; end

  def new
    @training = Training.new
  end

  def invitations
    @training.send_invitations!
    redirect_to section_trainings_path(section_id: current_section.to_param), notice: 'Notifications envoyées'
  end

  def edit; end

  def create
    @training = Training.new training_params
    @training.sections << current_section
    @training.groups = current_section.groups.where(id: params[:training][:group_ids])
    @training.save!
    redirect_to section_trainings_path(section_id: current_section.to_param), notice: 'Entrainement créé'
  end

  def update
    @training.assign_attributes(training_params)
    @training.groups = current_section.groups.where(id: params[:training][:group_ids])
    if @training.save
      redirect_with(fallback: section_training_path(current_section, @training), notice: 'Entrainement modifié')
    else
      render :edit, status: :unprocessable_content
    end
  end

  def repeat
    date = params['repeat_until'].to_date
    @training.repeat_until!(date)

    redirect_to section_training_path(section_id: current_section.to_param, id: @training.to_param),
                notice: 'Entrainement répété'
  end

  def destroy
    @training.destroy
    redirect_to section_trainings_path(section_id: current_section.to_param), notice: 'Entrainement supprimé'
  end

  def cancellation
    @training.cancel!(reason: params[:cancellation][:reason])
    redirect_with(fallback: section_training_path(current_section, @training))
  end

  def uncancel
    @training.uncancel!
    redirect_with(fallback: section_training_path(current_section, @training))
  end

  def presence_validation
    @players = current_section.players.sort_by(&:full_name)
  end

  private

  def training_params
    params.expect(training: %i[start_datetime end_datetime location_id group_ids max_capacity])
  end

  def set_current_training
    @training = Training.of_section(current_section).find_by(id: params[:id]) if params[:id]
  end
end

app/views/trainings/_form.html.slim
div class="flex flex-col space-y-8"
  = simple_form_for [current_section, @training] do |f|
    = f.input :start_datetime, as: :datetime, autofocus: true, html5: true
    = f.input :end_datetime, as: :datetime, html5: true
    = f.input :location_id, collection: Location.order('name ASC'), input_html: { data: { controller: 'ts--select' }, class: 'px-0 py-0' }
    = f.association :groups, collection: current_section.groups.where(season: Season.current).order("system DESC, name"), input_html: { data: { controller: 'ts--select' }, class: 'px-0 py-0' }, selected: current_section.group_every_players.id
    = f.input :max_capacity, input_html: { min: 1, max: 100, class: 'w-20' }
    = f.button :submit, value: 'Ajouter l\'entrainement', class: 'btn btn-primary'


  - if @training.persisted?
    = form_tag repeat_section_training_path(current_section, @training) do
      = label_tag 'Répéter j\'usqu\'au'
      div class="inline-flex space-x-1 ml-2"
        = date_field_tag :repeat_until, nil, required: :required, class: 'flex w-auto w-auto shadow-sm appearance-none border border-gray-300 rounded-sm w-full bg-white focus:outline-hidden focus:border-blue-500 text-gray-900 leading-4 transition-colors duration-200 ease-in-out datetime required'
        = submit_tag 'Répéter', class: 'btn btn-primary'

app/views/trainings/_training.html.slim
li.block.p-1.md:p-2 class=(training.cancelled? ? 'bg-red-200 hover:bg-red-300' : 'hover:bg-gray-100 odd:bg-gray-50')
  .flex.flex-col.md:flex-row
    / lieu et groupes
    div.flex.flex-col.justify-between.items-center.md:items-start
      .flex.text-xs.text-gray-500
        div
          svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"
            path fill-rule="evenodd" d="M9.69 18.933l.003.001C9.89 19.02 10 19 10 19s.11.02.308-.066l.002-.001.006-.003.018-.008a5.741 5.741 0 00.281-.14c.186-.096.446-.24.757-.433.62-.384 1.445-.966 2.274-1.765C15.302 14.988 17 12.493 17 9A7 7 0 103 9c0 3.492 1.698 5.988 3.355 7.584a13.731 13.731 0 002.273 1.765 11.842 11.842 0 00.976.544l.062.029.018.008.006.003zM10 11.25a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z" clip-rule="evenodd"
        = render partial: 'locations/gmaps_link', locals: { location: training.location }

      .text-center.md:text-left.text-xs.text-gray-600
        - training.groups.each do |group|
          span(title= group.description) = group.name


    / date
    .grow.flex.flex-col.items-center
      .flex.flex-row.items-center
        <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M5.75 2a.75.75 0 01.75.75V4h7V2.75a.75.75 0 011.5 0V4h.25A2.75 2.75 0 0118 6.75v8.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25v-8.5A2.75 2.75 0 014.75 4H5V2.75A.75.75 0 015.75 2zm-1 5.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h10.5c.69 0 1.25-.56 1.25-1.25v-6.5c0-.69-.56-1.25-1.25-1.25H4.75z" clip-rule="evenodd" />
        </svg>
        p.text-sm.font-medium.text-gray-900= l(training.start_datetime, format: "%a %d %b %R")
        - if training.max_capacity.present?
          p.text-xs.text-gray-800.ml-2=< "(#{training.max_capacity} max)"
      - if training.cancelled?
        p.block.text-sm.font-bold.text-gray-600
          'ENTRAINEMENT ANNULÉ
          = " : #{training.cancel_reason}" if training.cancel_reason.present?

    / présences
    div
      .flex.flex-col.items-center.md:items-end
        - if !training.cancelled?
          .flex.flex-row-reverse
            = render partial: 'matches/presences', locals: {link_url: section_training_path(training, section_id: current_section.to_param), nb_presents: training.nb_presents, nb_not_presents: training.nb_not_presents, nb_no_response: training.nb_presence_not_set}

          - if current_user.player_of?(current_section)
            .flex.flex-row-reverse.mt-2
              .flex.flex-nowrap
                - if training.users.include?(current_user)
                  - if current_user.present_for?(training).nil?
                    - if training.max_capacity_reached?
                      div class='inline-flex items-center rounded-sm border border-transparent bg-red-100 px-1.5 py-1 text-xs font-medium text-red-700'
                        = "Complet"
                    - else
                      = button_to 'Présent', section_user_training_training_presences_path(current_section, current_user, training), method: :post, class: 'inline-flex items-center rounded-sm border border-transparent bg-indigo-100 px-1.5 py-1 text-xs font-medium text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 '
                    = button_to 'Absent', section_user_training_training_presences_path(current_section, current_user, training), method: :delete, class: 'inline-flex items-center rounded-sm border border-transparent bg-indigo-100 px-1.5 py-1 text-xs font-medium text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 ml-1'
                  - elsif current_user.present_for?(training) == true
                    .inline-flex.items-center.rounded-full.bg-green-100.px-2.5.py-0.5.text-xs.font-medium.text-green-800 Présent
                    = button_to "m'indiquer absent", section_user_training_training_presences_path(current_section, current_user, training), method: :delete, class: 'inline-flex items-center px-1 py-0.5 text-xs text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 underline ml-1'
                  - else
                    .inline-flex.items-center.rounded-full.bg-red-100.px-2.5.py-0.5.text-xs.font-medium.text-red-800 Absent
                    - if training.max_capacity_reached?
                      div class='inline-flex items-center px-1 py-0.5 text-xs text-red-700 ml-1'
                        = "Complet"
                    - else
                      = button_to "m'indiquer présent", section_user_training_training_presences_path(current_section, current_user, training), method: :post, class: 'inline-flex items-center px-1 py-0.5 text-xs text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 underline ml-1'

    / actions
    - if current_user.coach_of?(current_section)
      .flex.flex-col.justify-center.md:ml-2.mt-2.md:mt-0
        .flex.flex-row.justify-center
          - if training.cancelled?
            .flex.items-center
              = button_to 'Rétablir', uncancel_section_training_path(training, section_id: current_section), method: :delete, id: "training_invitations_#{training.id}", class: 'inline-flex items-center rounded-sm border border-transparent bg-indigo-600 px-1.5 py-1 text-xs font-medium text-white shadow-xs hover:bg-indigo-700 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2'
          - else
            = link_to presence_validation_section_training_path(training, section_id: current_section.to_param) do
              svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
                path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z"
                path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"

            = link_to edit_section_training_path(training, section_id: current_section.to_param) do
              svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
                path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"

            = button_to invitations_section_training_path(training, section_id: current_section), title: 'Relancer les indécits',id: "training_invitations_#{training.id}", form: { data: {turbo_confirm: 'Renvoyer les mails pour les indécits ?'} }, method: :post, class: 'align-middle' do
              svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
                path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"

            .flex.items-center data-controller="dropdown"
              a.text-red-700 href="#" title="Annuler l'entrainement" data-action="dropdown#toggle:prevent"
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m6 4.125l2.25 2.25m0 0l2.25 2.25M12 13.875l2.25-2.25M12 13.875l-2.25 2.25M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
                </svg>

              .hidden id="cancel-training-#{training.id}" aria-expanded="false" data-dropdown-target="menu"
                = form_tag(cancellation_section_training_path(training, section_id: current_section), method: :post) do
                  = text_field(:cancellation, :reason, placeholder: 'Raison de l\'annulation')
                  = submit_tag('Annuler l\'entrainement', class: 'inline-flex items-center rounded-sm border border-transparent bg-indigo-600 px-1.5 py-1 text-xs font-medium text-white shadow-xs hover:bg-indigo-700 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2')

app/views/trainings/_trainings.html.slim
.overflow-hidden.bg-white.shadow-sm.sm:rounded-md
  ul.divide-y.divide-gray-200 role="list"
    - if trainings.empty?
      .p-4
        'Aucun entrainement prévu dans les prochaines semaines
    - else
      = render trainings

app/views/trainings/edit.html.haml
%h2 Prévoir un entrainement

= render 'form'

app/views/trainings/index.html.slim
.sm:flex.sm:items-center
  .sm:flex-auto
    h1.text-xl.font-semibold.text-gray-900= "#{@trainings.total_count} entraînements"

  - if current_user.coach_of?(current_section)
    .mt-4.mt-0.ml-16.flex-none
      = link_to 'Ajouter un entrainement', new_section_training_path(section_id: current_section), class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-xs hover:bg-indigo-700 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2"

= render partial: 'trainings/trainings', object: @trainings

= paginate @trainings

app/views/trainings/new.html.haml
%h2 Prévoir un entrainement

= simple_form_for [current_section, @training] do |f|
  = f.input :start_datetime, :as => :datetime, :autofocus => true
  = f.input :end_datetime, :as => :datetime
  = f.input :location_id, collection: Location.order('name ASC')
  = f.association :groups, collection: current_section.groups.where(season: Season.current).order("system DESC, name"), input_html: {size: 10}, selected: current_section.group_every_players.id
  = f.button :submit, value: 'Ajouter l\'entrainement', class: 'btn btn-primary'

app/views/trainings/new.html.slim
.flex.items-center
  .sm:flex-auto
    h1.text-xl.font-semibold.text-gray-900 Prévoir un entrainement

= render 'form'

app/views/trainings/presence_validation.html.slim
h2.text-4xl
  'Entrainement du
  = @training.start_datetime.strftime("%-d/%-m/%Y %-HH%-M")

- players_and_color = [[@training.presents.sort_by(&:full_name), :green], [@training.not_presents.sort_by(&:full_name), :red], [@training.presence_not_set.sort_by(&:full_name), :yellow]]

div.w-full
  - players_and_color.each do |players, color|
    - players.each do |player|
      = render partial: 'training_presences/show', locals: { training: @training, player: player, color: color }

app/views/trainings/show.html.haml
%h2
  Entrainement du
  = @training.start_datetime.strftime("%-d/%-m/%Y %-HH%-M")

  - if current_user.coach_of?(current_section)
    .action
      = link_to edit_section_training_path(current_section, @training) do
        %span.glyphicon.glyphicon-pencil
      = link_to section_training_path(@training, section_id: current_section), :method => :delete, :data => { :confirm => 'Are you sure?' } do
        %span.glyphicon.glyphicon-trash

%p
  = render partial: 'locations/gmaps_link', locals: {location: @training.location}
  %br
  Groupes :
  = @training.groups.map(&:name).join(", ")

.row
  .col-md-4
    .panel.panel-success
      .panel-heading
        - training_presents = @training.presents
        = training_presents.size
        Joueurs présents
      %ul.list-group
        - training_presents.sort_by(&:full_name).each do |user|
          %li.list-group-item= user.full_name
  .col-md-4
    .panel.panel-danger
      .panel-heading
        - training_not_presents = @training.not_presents
        = training_not_presents.size
        Joueurs non présents
      .list-group
        - training_not_presents.sort_by(&:full_name).each do |user|
          %li.list-group-item= user.full_name
  .col-md-4
    .panel.panel-warning
      .panel-heading
        - training_presence_not_set = @training.presence_not_set
        = training_presence_not_set.size
        Pas de réponse
      .list-group
        - training_presence_not_set.sort_by(&:full_name).each do |user|
          %li.list-group-item= user.full_name