config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :blocked_addresses
    resources :calendars
    resources :championships
    resources :clubs
    resources :club_admin_roles
    resources :days
    resources :duty_tasks
    resources :enrolled_team_championships
    resources :groups
    resources :locations
    resources :matches
    resources :match_availabilities
    resources :match_selections
    resources :participations
    resources :seasons
    resources :sections
    resources :section_user_invitations
    resources :selections
    resources :teams
    resources :trainings
    resources :training_invitations
    resources :training_presences
    resources :users

    root to: 'users#index'
  end
  resources :days

  resources :championships

  resources :sections, only: %i[show] do
    resources :duty_tasks do
      collection do
        get 'leaderboard'
      end
    end
    resources :section_user_invitations, path: 'user_invitations', only: %i[new show create index]
    resources :trainings do
      resources :users, only: [] do
        get 'training_presence' => 'training_presences#show'
      end
      member do
        get 'presence_validation'
        post 'invitations'
        post 'cancellation'
        post 'repeat'
        delete 'uncancel'
      end
    end
    resources :absences, only: %i[index]
    resources :users, path: 'members' do
      resources :trainings, only: [] do
        resources :training_presences, only: %i[create show]
        delete 'training_presences' => 'training_presences#destroy'
        post 'confirm_presence' => 'training_presences#confirm_presence'
      end
      resources :absences, only: %i[index create edit update destroy new]
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end

    resources :participations_renewal, only: %i[index create]

    resources :groups do
      post 'users' => 'groups#add_users', as: 'add_users'
      resources :users, only: [:destroy]
    end
    resources :matches do
      member do
        post :selection
        resources :selections, only: [:destroy]
        post 'invitations'
      end
    end
    resources :championships do
      member do
        get :merge_calendar_form
        post :merge_calendar
      end
      resources :matches
      resources :enrolled_team_championships, only: %i[index create destroy]
      resources :burns, only: %i[index create destroy]
    end
    resources :days, only: %i[create update] do
      resources :selections, only: [:index]
    end
    resources :calendars, only: %i[index create edit update]
    resources :days, only: [:create]
    resources :locations, only: [:create]
    resources :teams, only: %i[create show destroy new]
    resources :channels do
      resources :messages, only: %i[create destroy]
    end
    resources :events, only: %i[index]

    patch 'player_ffhb_association'
    delete 'dissociate_player'
  end

  resources :club_admin_roles, only: %i[index show]

  resources :teams, only: %i[index show]

  resources :clubs, only: %i[index show] do
    resources :sections, only: %i[index new create destroy edit update]
  end

  devise_for :users, except: %i[show]

  resources :users, only: %i[show edit update] do
    member do
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end
  end

  resources :messages, only: [] do
    collection do
      post 'mark_as_read'
    end
  end

  resources :webpush_subscriptions, only: [:create], constraints: { format: :json }

  authenticate :user, ->(u) { u.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  root to: 'visitors#index'

  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  get '.well-known/acme-challenge/4k3hP8fSRgCKf0inS8qYK9LYs8sU10ZMfSiYs8-Mcxg' => 'visitors#letsencrypt'
  get '.well-known/acme-challenge/DNyCHVFZJQpss-fIqj5vX317OwOjUfwRklgsSJMAJXo-Mcxg' => 'visitors#letsencrypt'

  get '.stimulus', to: 'visitors#stimulus'
end
# rubocop:enable Metrics/BlockLength

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :channel
  belongs_to :parent_message, class_name: 'Message', optional: true
  has_many :child_messages, class_name: 'Message', foreign_key: :parent_message_id, dependent: :destroy,
                            inverse_of: :parent_message
  has_many :user_channel_messages, inverse_of: :message, dependent: :destroy
  # has_many :reactions, dependent: :destroy

  # Validations
  validates :content, presence: true

  after_create_commit -> { broadcast_append_to channel }
  after_create_commit :async_notify_users

  has_rich_text :content

  def notify_users
    title = "New message in #{channel.section.name}"
    body = "#{user.short_name}: #{content.to_plain_text.truncate(50)}"

    channel.section.users.each do |user|
      next if user == self.user

      WebpushService.send_notification_to_all_user_subscriptions(user, title:, body:)
    end
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_channel, except: [:mark_as_read]

  def create
    @message = @channel.messages.new(message_params)
    @message.user = current_user

    respond_to do |format|
      format.html { redirect_to section_channel_path(current_section, @channel) }
      if @message.save
        format.turbo_stream
        format.js
      else
        format.js { render json: { errors: @message.errors }, status: :unprocessable_content }
      end
    end
  end

  def destroy
    @message = @channel.messages.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to section_channel_path(current_section, @channel) }
      format.turbo_stream
      format.js
    end
  end

  def mark_as_read
    message_ids = params[:message_ids].presence || []
    message_ids = message_ids.map(&:to_i)

    current_user.read!(message_ids)

    render json: {}
  end

  private

  def set_channel
    @channel = Channel.find(params[:channel_id])
  end

  def message_params
    params.expect(message: [:content])
  end
end

app/views/messages/_message.erb
<div class="flex px-4 py-3">
  <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300">
    <!-- image of a gravatar based on email hash -->
    <img src="https://www.gravatar.com/avatar/<%= Digest::MD5.hexdigest(message.user.email) %>?d=identicon" class="h-10 w-10 rounded">
  </div>
  <div class="ml-2 messages">
    <div class="-mt-1">
      <span class="text-sm font-semibold"><%= message.user.short_name %></span>
      <span class="ml-1 text-xs text-gray-500">
        <%= message.created_at.strftime("%H:%M") %>
      </span>
    </div>
    <%= auto_link(simple_format(message.content), html: { :target => '_blank' }) %> 
    <%# <div class="flex space-x-2 mt-1">
      <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
        <span>🤷</span>
        <span class="ml-1 font-medium">2</span>
      </button>
    </div> %>
  </div>
</div>



<%# 
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Sam</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">Anyone know if Frodo is awake yet?</p>
          <div class="flex space-x-2 mt-1">
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>🤷</span>
              <span class="ml-1 font-medium">2</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex flex-col items-center mt-2">
        <hr class="w-full">
        <span class="flex items-center justify-center -mt-3 bg-white h-6 px-3 rounded-full border text-xs font-semibold mx-auto">Today</span>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Elrond</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">Strangers from distant lands, friends of old. You have been summoned here to answer the threat of Mordor. Middle-Earth stands upon the brink of destruction. None can escape it. You will unite or you will fall. Each race is bound to this fate–this one doom. (gestures to the pedestal) Bring forth the Ring, Frodo.</p>
          <div class="flex space-x-2 mt-1">
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>❤️</span>
              <span class="ml-1 font-medium">5</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Boromir</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">So it is true…</p>
          <p class="text-sm">It is a gift. A gift to the foes of Mordor. Why not use this Ring? (paces) Long has my father, the Steward of Gondor, kept the forces of Mordor at bay. By the blood of our people are your lands kept safe! Give Gondor the weapon of the Enemy. Let us use it against him!</p>
          <div class="flex space-x-2 mt-1">
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>👎</span>
              <span class="ml-1 font-medium">1</span>
            </button>
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>🤔</span>
              <span class="ml-1 font-medium">3</span>
            </button>
          </div>
          <div class="flex items-center mt-2">
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300"></div>
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300 ml-1"></div>
            <a class="text-blue-600 text-xs font-medium ml-1" href="#">4 replies</a>
            <span class="text-xs text-gray-600 ml-1">Last reply today at 03:45</span>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Aragorn</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">You cannot wield it! None of us can. The One Ring answers to Sauron alone. It has no other master.</p>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Boromir</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">And what would a ranger know of this matter?</p>
          <div class="flex space-x-2 mt-1">
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>😲</span>
              <span class="ml-1 font-medium">2</span>
            </button>
          </div>
          <div class="flex items-center mt-2">
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300"></div>
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300 ml-1"></div>
            <a class="text-blue-600 text-xs font-medium ml-1" href="#">4 replies</a>
            <span class="text-xs text-gray-600 ml-1">Last reply today at 03:45</span>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Legolas</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">This is no mere ranger. He is Aragorn, son of Arathorn. You owe him your allegiance.</p>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Boromim</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">Aragorn? This… is Isildur’s heir?</p>
          <div class="flex items-center mt-2">
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300"></div>
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300 ml-1"></div>
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300 ml-1"></div>
            <a class="text-blue-600 text-xs font-medium ml-1" href="#">3 replies</a>
            <span class="text-xs text-gray-600 ml-1">Last reply today at 03:45</span>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Boromir</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">Gondor has no king. Gondor needs no king.</p>
          <div class="flex items-center mt-2">
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300"></div>
            <div class="h-6 w-6 rounded flex-shrink-0 bg-gray-300 ml-1"></div>
            <a class="text-blue-600 text-xs font-medium ml-1" href="#">4 replies</a>
            <span class="text-xs text-gray-600 ml-1">Last reply today at 03:45</span>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Gandalf</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">Aragorn is right. We cannot use it.</p>
          <div class="flex space-x-2 mt-1">
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>👍</span>
              <span class="ml-1 font-medium">6</span>
            </button>
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>🧙‍</span>
              <span class="ml-1 font-medium">3</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Elrond</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">You have only one choice. The Ring must be destroyed.</p>
          <div class="flex space-x-2 mt-1">
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>💍</span>
              <span class="ml-1 font-medium">1</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Gimli</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">What are we waiting for?</p>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Elrond</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">The Ring cannot be destroyed, Gimli, son of Gloin by any craft that we here possess. The Ring was made in the fires of Mount Doom. Only there can it be unmade. It must be taken deep into Mordor and cast back into the fiery chasm from whence it came.</p>
          <p class="text-sm">One of you must do this.</p>
          <div class="flex space-x-2 mt-1">
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>🗻</span>
              <span class="ml-1 font-medium">2</span>
            </button>
            <button class="flex items-center pl-1 pr-2 h-5 bg-gray-300 hover:bg-gray-400 rounded-full text-xs">
              <span>🔥</span>
              <span class="ml-1 font-medium">3</span>
            </button>
          </div>
        </div>
      </div>
      <div class="flex px-4 py-3">
        <div class="h-10 w-10 rounded flex-shrink-0 bg-gray-300"></div>
        <div class="ml-2">
          <div class="-mt-1">
            <span class="text-sm font-semibold">Boromir</span>
            <span class="ml-1 text-xs text-gray-500">01:26</span>
          </div>
          <p class="text-sm">One does not simply walk into Mordor. Its black gates are guarded by more than just orcs. There is evil there that does not sleep. And the great Eye is ever watchful. It is a barren wasteland riddled with fire and ash and dust. The very air you breathe is a poisonous fume. Not with ten thousand men could you do this. It is folly!</p>
        </div>
      </div> %>

app/views/messages/_message.html.slim
div id="message_#{message.id}" class="flex px-4 py-3 message #{ (Current.user.present? && Current.user == message.user) && "place-content-end"} #{Current.user.present? && Current.user.read?(message) ? "read" : "unread"}"
  div class="h-8 w-8 flex-shrink-0 bg-gray-300"
    - if message.user.avatar.attached?
      img src="#{rails_storage_proxy_path(message.user.avatar.variant(:thumb))}" class="h-8 w-8 rounded-sm"
    - else
      img src="https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(message.user.email)}?d=identicon" class="h-8 w-8 rounded-sm"
  div class="ml-2 bg-white rounded-xl px-2"
    div class="-mt-1"
      span class="text-sm"= message.user.short_name
    div class="flex flex-row"
      span class="text-lg font-semibold"
        = message.content
    div class="-mt-2 ml-36 text-xs text-gray-400 text-right align-bottom"
        = message.created_at.strftime("%d/%m %H:%M")
  - if Current.user == message.user
    = button_to section_channel_message_path(Current.section, message.channel, message), method: :delete, class: "px-2", title: "Supprimer le message" do
      svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
        path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"

app/views/messages/create.turbo_stream.slim
/ keep this file empty, render is made by broadcast

app/views/messages/destroy.turbo_stream.slim
turbo-stream action="remove" target="message_#{ @message.id }"