config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :blocked_addresses
    resources :calendars
    resources :championships
    resources :clubs
    resources :club_admin_roles
    resources :days
    resources :duty_tasks
    resources :enrolled_team_championships
    resources :groups
    resources :locations
    resources :matches
    resources :match_availabilities
    resources :match_selections
    resources :participations
    resources :seasons
    resources :sections
    resources :section_user_invitations
    resources :selections
    resources :teams
    resources :trainings
    resources :training_invitations
    resources :training_presences
    resources :users

    root to: 'users#index'
  end
  resources :days

  resources :championships

  resources :sections, only: %i[show] do
    resources :duty_tasks do
      collection do
        get 'leaderboard'
      end
    end
    resources :section_user_invitations, path: 'user_invitations', only: %i[new show create index]
    resources :trainings do
      resources :users, only: [] do
        get 'training_presence' => 'training_presences#show'
      end
      member do
        get 'presence_validation'
        post 'invitations'
        post 'cancellation'
        post 'repeat'
        delete 'uncancel'
      end
    end
    resources :absences, only: %i[index]
    resources :users, path: 'members' do
      resources :trainings, only: [] do
        resources :training_presences, only: %i[create show]
        delete 'training_presences' => 'training_presences#destroy'
        post 'confirm_presence' => 'training_presences#confirm_presence'
      end
      resources :absences, only: %i[index create edit update destroy new]
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end

    resources :participations_renewal, only: %i[index create]

    resources :groups do
      post 'users' => 'groups#add_users', as: 'add_users'
      resources :users, only: [:destroy]
    end
    resources :matches do
      member do
        post :selection
        resources :selections, only: [:destroy]
        post 'invitations'
      end
    end
    resources :championships do
      member do
        get :merge_calendar_form
        post :merge_calendar
      end
      resources :matches
      resources :enrolled_team_championships, only: %i[index create destroy]
      resources :burns, only: %i[index create destroy]
    end
    resources :days, only: %i[create update] do
      resources :selections, only: [:index]
    end
    resources :calendars, only: %i[index create edit update]
    resources :days, only: [:create]
    resources :locations, only: [:create]
    resources :teams, only: %i[create show destroy new]
    resources :channels do
      resources :messages, only: %i[create destroy]
    end
    resources :events, only: %i[index]

    patch 'player_ffhb_association'
    delete 'dissociate_player'
  end

  resources :club_admin_roles, only: %i[index show]

  resources :teams, only: %i[index show]

  resources :clubs, only: %i[index show] do
    resources :sections, only: %i[index new create destroy edit update]
  end

  devise_for :users, except: %i[show]

  resources :users, only: %i[show edit update] do
    member do
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end
  end

  resources :messages, only: [] do
    collection do
      post 'mark_as_read'
    end
  end

  resources :webpush_subscriptions, only: [:create], constraints: { format: :json }

  authenticate :user, ->(u) { u.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  root to: 'visitors#index'

  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  get '.well-known/acme-challenge/4k3hP8fSRgCKf0inS8qYK9LYs8sU10ZMfSiYs8-Mcxg' => 'visitors#letsencrypt'
  get '.well-known/acme-challenge/DNyCHVFZJQpss-fIqj5vX317OwOjUfwRklgsSJMAJXo-Mcxg' => 'visitors#letsencrypt'

  get '.stimulus', to: 'visitors#stimulus'
end
# rubocop:enable Metrics/BlockLength

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  belongs_to :section
  belongs_to :season

  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships
  has_many :group_trainings, dependent: :destroy
  has_many :trainings, through: :group_trainings

  validates :name, presence: true

  scope :non_system, -> { where(system: false) }

  def add_user!(user)
    users << user unless users.include?(user)
    self
  end

  def remove_user!(user, force: false)
    raise 'You cannot remove user from system group' if system? && !force

    users.delete(user)
  end

  def copy_to_current_season
    Group.create!(section:, season: Season.current,
                  name:, system:, users:,
                  color:, description:, role:)
  end
end

app/controllers/admin/groups_controller.rb
# frozen_string_literal: true

module Admin
  class GroupsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :find_group

  def index
    @groups = current_section.groups.where(season: Season.current).order(:system, :name)
  end

  def show
    @users = @group.users.includes(:participations, :groups)
    @last_trainings, @presences_by_user_and_training = prepare_training_presences(current_section, @users)
  end

  def new
    @group = Group.new section: current_section
  end

  def create
    @group = Group.new group_params
    @group.section = current_section
    @group.season = Season.current
    if @group.save
      redirect_to section_group_path(current_section, @group), notice: 'Groupe créé'
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @group.update group_params
      redirect_to section_group_path(current_section, @group), notice: 'Groupe modifié'
    else
      render :edit, status: :unprocessable_content
    end
  end

  def add_users
    user = User.find params[:user_id]
    @group.add_user! user
    redirect_to section_group_path(current_section, @group), notice: 'Joueur ajouté au groupe'
  end

  def destroy
    @group.destroy
    redirect_to section_groups_path(current_section), notice: "Groupe '#{@group.name}' supprimé"
  end

  private

  def group_params
    params.expect(group: %i[name color description])
  end

  def find_group
    id = params[:id] || params[:group_id]
    @group = Group.find id if id
  end
end

app/views/groups/_form.html.haml
= simple_form_for([current_section, @group]) do |f|
  = f.input :name
  = f.input :description
  = f.input :color, input_html: {type: :color}
  = f.button :submit, class: 'btn btn-primary'

app/views/groups/_form.html.slim
= simple_form_for([current_section, @group]) do |f|
  = f.input :name
  = f.input :description
  = f.input :color, input_html: {type: :color, style: 'padding: 0'}
  = f.button :submit, class: 'btn btn-primary'

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', section_group_path(current_section, @group)
\|
= link_to 'Back', section_groups_path(current_section)

app/views/groups/index.html.slim
.flex.items-center
  .sm:flex-auto
    h1.text-xl.font-semibold.text-gray-900= "#{@groups.count} groupes"

  - if current_section && current_user.coach_of?(current_section)
    .mt-4.mt-0.ml-16.flex-none
      = link_to 'Ajouter un groupe', new_section_group_path(current_section), class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-xs hover:bg-indigo-700 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2"

div class="mt-8 flex flex-col"
  div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8"
    div class="inline-block w-full py-2 align-middle md:px-6 lg:px-8"
      div class="overflow-hidden shadow-sm ring-1 ring-black ring-opacity-5 md:rounded-lg"
        table class="w-full divide-y divide-gray-300"
          thead class="bg-gray-50"
            tr
              th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6" Couleur
              th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6" Nom
              th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6" Description
              - if current_section && current_user.coach_of?(current_section)
                th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6"
                  span class="sr-only" Supprimer
          tbody class="divide-y divide-gray-200 bg-white"
            - @groups.each do |group|
              tr
                td scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm text-gray-900 sm:pl-6" style="background-color: #{group.color}"
                td scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm text-gray-900 sm:pl-6 text-indigo-600"= link_to group.name, section_group_path(current_section, group), class: 'hover:underline'
                td scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm text-gray-900 sm:pl-6"= group.description
                - if current_section && current_user.coach_of?(current_section)
                  td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6"
                    = button_to section_group_path(current_section, group), method: :delete, form: {data: {turbo_confirm: "Supprimer le groupe #{group.name} ?"}} do
                      span.sr-only= "Supprimer le group #{group.name}"
                      svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
                        path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" /

app/views/groups/new.html.haml
%h1 Nouveau group

= render 'form'

= link_to 'Annuler', section_groups_path(current_section)

app/views/groups/show.html.slim
- require 'colorist'

h2
  = @group.name
  - if !@group.system? && current_section && current_user.coach_of?(current_section)
    .action
      = link_to edit_section_group_path(current_section, @group) do
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" /></svg>
p
  = @group.description
.panel.panel-info
  - if @group.color
    - begin
      - invert = Colorist::Color.from_string(@group.color).invert
      - style = "background-color: #{@group.color}; color: #{invert}"
    - rescue
      - style = ''
  - else
    - style = ''
  .panel-heading{style: style}
    strong= "#{@users.count} membres"
  .panel-body
    - if !@group.system? && current_section && current_user.coach_of?(current_section)
      = form_tag section_group_add_users_path(current_section, @group), class: 'flex flex-row' do
        = select_tag 'user_id', options_from_collection_for_select(current_section.members - @users, :id, :full_name), include_blank: true, data: { controller: 'ts--select' }, class: 'w-72'

        button class="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-xs hover:bg-indigo-700 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 ml-2" type='submit' Ajouter
    = render partial: 'users/users', object: @users, locals: { group: @group }