config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  namespace :admin do
    resources :admin_users
    resources :blocked_addresses
    resources :calendars
    resources :championships
    resources :clubs
    resources :club_admin_roles
    resources :days
    resources :duty_tasks
    resources :enrolled_team_championships
    resources :groups
    resources :locations
    resources :matches
    resources :match_availabilities
    resources :match_selections
    resources :participations
    resources :seasons
    resources :sections
    resources :section_user_invitations
    resources :selections
    resources :teams
    resources :trainings
    resources :training_invitations
    resources :training_presences
    resources :users

    root to: 'users#index'
  end
  resources :days

  resources :championships

  resources :sections, only: %i[show] do
    resources :duty_tasks do
      collection do
        get 'leaderboard'
      end
    end
    resources :section_user_invitations, path: 'user_invitations', only: %i[new show create index]
    resources :trainings do
      resources :users, only: [] do
        get 'training_presence' => 'training_presences#show'
      end
      member do
        get 'presence_validation'
        post 'invitations'
        post 'cancellation'
        post 'repeat'
        delete 'uncancel'
      end
    end
    resources :absences, only: %i[index]
    resources :users, path: 'members' do
      resources :trainings, only: [] do
        resources :training_presences, only: %i[create show]
        delete 'training_presences' => 'training_presences#destroy'
        post 'confirm_presence' => 'training_presences#confirm_presence'
      end
      resources :absences, only: %i[index create edit update destroy new]
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end

    resources :participations_renewal, only: %i[index create]

    resources :groups do
      post 'users' => 'groups#add_users', as: 'add_users'
      resources :users, only: [:destroy]
    end
    resources :matches do
      member do
        post :selection
        resources :selections, only: [:destroy]
        post 'invitations'
      end
    end
    resources :championships do
      member do
        get :merge_calendar_form
        post :merge_calendar
      end
      resources :matches
      resources :enrolled_team_championships, only: %i[index create destroy]
      resources :burns, only: %i[index create destroy]
    end
    resources :days, only: %i[create update] do
      resources :selections, only: [:index]
    end
    resources :calendars, only: %i[index create edit update]
    resources :days, only: [:create]
    resources :locations, only: [:create]
    resources :teams, only: %i[create show destroy new]
    resources :channels do
      resources :messages, only: %i[create destroy]
    end
    resources :events, only: %i[index]

    patch 'player_ffhb_association'
    delete 'dissociate_player'
  end

  resources :club_admin_roles, only: %i[index show]

  resources :teams, only: %i[index show]

  resources :clubs, only: %i[index show] do
    resources :sections, only: %i[index new create destroy edit update]
  end

  devise_for :users, except: %i[show]

  resources :users, only: %i[show edit update] do
    member do
      match 'training_presences', via: %i[get post]
      match 'match_availabilities', via: %i[get post]
    end
  end

  resources :messages, only: [] do
    collection do
      post 'mark_as_read'
    end
  end

  resources :webpush_subscriptions, only: [:create], constraints: { format: :json }

  authenticate :user, ->(u) { u.super_admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  root to: 'visitors#index'

  get 'switch_user', to: 'switch_user#set_current_user'
  get 'switch_user/remember_user', to: 'switch_user#remember_user'
  get '.well-known/acme-challenge/4k3hP8fSRgCKf0inS8qYK9LYs8sU10ZMfSiYs8-Mcxg' => 'visitors#letsencrypt'
  get '.well-known/acme-challenge/DNyCHVFZJQpss-fIqj5vX317OwOjUfwRklgsSJMAJXo-Mcxg' => 'visitors#letsencrypt'

  get '.stimulus', to: 'visitors#stimulus'
end
# rubocop:enable Metrics/BlockLength

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord # rubocop:disable Metrics/ClassLength
  belongs_to :championship
  belongs_to :location, optional: true
  belongs_to :day

  # TODO: match should link to enrolled teams instead of teams
  belongs_to :local_team, class_name: 'Team'
  belongs_to :visitor_team, class_name: 'Team'

  has_many :selections, inverse_of: :match, dependent: :destroy
  has_many :match_availabilities, inverse_of: :match, dependent: :destroy
  has_many :match_invitations, inverse_of: :match, dependent: :destroy

  scope :join_day, -> { joins('LEFT OUTER JOIN days ON days.id = matches.day_id') }
  scope :date_ordered, -> { order(Arel.sql('LEAST(days.period_end_date, start_datetime) ASC')) }

  scope :with_start_between, lambda { |start_period, end_period|
                               where(start_datetime: start_period..end_period)
                             }
  scope :on_days, ->(days) { where('DATE(start_datetime) IN (?)', days) }

  delegate :burned?, to: :championship

  def date
    if start_datetime
      start_datetime.to_fs(:short)
    elsif day
      day.name
    elsif prevision_period_start && prevision_period_end
      "(#{prevision_period_start.to_fs(:short)} - #{prevision_period_end.to_fs(:short)})"
    else
      ''
    end
  end

  def users
    section_ids = Team.joins(:team_sections)
                      .where(id: [local_team_id, visitor_team_id])
                      .pluck('team_sections.section_id')
                      .uniq

    User.joins(:participations).where(participations: {
                                        season: Season.current,
                                        role: Participation::PLAYER,
                                        section_id: section_ids
                                      })
  end

  def _availables
    away_user_ids = aways.pluck(:id)
    match_availabilities.includes(:user).where(available: true).where.not(user_id: away_user_ids)
  end

  def availables
    _availables.map(&:user)
  end

  def nb_availables
    _availables.count
  end

  def _not_availables
    match_availabilities.includes(:user).where(available: false)
  end

  def not_availables
    (_not_availables.map(&:user) + aways).uniq
  end

  def aways
    users.joins(:absences)
         .where('absences.start_at <= ? AND absences.end_at >= ?', start_datetime || day.period_start_date, end_datetime || day.period_end_date)
  end

  def nb_aways
    aways.count
  end

  def nb_not_availables
    not_availables.count
  end

  def nb_availability_not_set
    availability_not_set.size
  end

  def availability_not_set
    users.uniq - availables - not_availables
  end

  def self.send_availability_mail_for_next_weekend
    User.where("email not like '%@example.com'").active_this_season.each do |user|
      next_7_days_matches = user.next_7_days_matches
      UserMailer.send_match_invitation(next_7_days_matches.to_a, user) unless next_7_days_matches.empty?
    end
  end

  def self.of_next_7_days(date: DateTime.now)
    start_period = date.at_beginning_of_week
    end_period = start_period.at_end_of_week
    Match.with_start_between(start_period, end_period)
  end

  def teams
    Team.where(id: [local_team_id, visitor_team_id])
  end

  def selections(team)
    Selection.includes(:user).where(match: self, team:)
  end

  def meeting_datetime
    super || start_datetime&.send(:-, 1.hour)
  end

  def ffhb_sync! # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    if ffhb_key.blank?
      logger.warn "No ffhb_key for match #{id}"
      return
    end

    match_details = FfhbService.instance.fetch_match_details(*ffhb_key.split)
    if match_details['rencontre']['date'].present?
      self.start_datetime = Time.find_zone('UTC').parse(match_details['rencontre']['date'])
      self.day = championship.find_or_create_day_for(start_datetime)
    end

    self.local_score = match_details['rencontre']['equipe1Score']&.to_i
    self.visitor_score = match_details['rencontre']['equipe2Score']&.to_i

    ffhb_id = match_details['rencontre']['equipementId']
    if ffhb_id.present?
      location = Location.find_by(ffhb_id:)
      if location.blank?
        rencontre_details = FfhbService.instance.fetch_rencontre_salle(*ffhb_key.split)
        name = rencontre_details['equipement']['libelle']
        address = <<~TEXT.chomp
          #{rencontre_details['equipement']['libelle']}
          #{rencontre_details['equipement']['rue']}
          #{rencontre_details['equipement']['codePostal']} #{rencontre_details['equipement']['ville']}
        TEXT

        location = Location.create!(name:, address:, ffhb_id:)
      end
      self.location = location
    end

    save!
  rescue FfhbServiceError => e
    Sentry.capture_message(
      'FFHB sync failed for match - possibly deleted match (team banished?)',
      level: :warning,
      extra: {
        error_message: e.message,
        match_id: id,
        match_ffhb_key: ffhb_key,
        championship_id: championship_id,
        championship_ffhb_key: championship.ffhb_key,
        season_id: championship.season_id
      }
    )
    logger.warn "FFHB sync failed for match #{id}: #{e.message}"
  end

  def calculated_start_datetime
    start_datetime || day&.period_start_date
  end
end

app/controllers/admin/matches_controller.rb
# frozen_string_literal: true

module Admin
  class MatchesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

class MatchesController < ApplicationController
  include PrefetchMatchData

  def index
    @section = Section.find params[:section_id]
    @next_matches = @section.next_matches(end_date: 1.year.from_now).includes(
      :local_team,
      :visitor_team,
      :day,
      :location,
      :championship,
      match_availabilities: :user
    )

    @current_user_is_player = current_user.player_of?(@section)
    preload_current_user_availabilities
    precompute_match_availability_counts
  end

  def show
    @match = Match.find params[:id]
    day = @match.day
    return if day.blank?

    @day_selections = Selection.joins(match: :day).where(matches: { day_id: day.id }).includes(:user, :team)
    @users_already_selected = @day_selections.map(&:user).uniq
    @team_by_user = {}
    @day_selections.each { |selection| @team_by_user[selection.user] = selection.team }
  end

  def new
    @section_team = Team.find_by(id: params[:section_team_id])
    @match = Match.new match_params
    @championship = @match.championship || Championship.new

    return unless params[:adversary_team_id].present? && @championship.persisted?

    @championship.enroll_team! Team.find_by(id: params[:adversary_team_id])
  end

  def edit
    @championship = Championship.find(params[:championship_id])
    @match = Match.find params[:id]
  end

  def create
    @championship = Championship.find(params[:match][:championship_id])
    @match = Match.new match_params
    if @match.save
      redirect_to section_championship_path(current_section, @championship), notice: 'Match créé'
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    @championship = Championship.find(params[:championship_id])
    @match = Match.find params[:id]
    if @match.update match_params
      redirect_to section_championship_path(current_section, @championship)
    else
      render :edit, status: :unprocessable_content
    end
  end

  def selection
    @user = User.find(params[:user_id])
    team = Team.find(params[:team_id])
    @match = Match.find(params[:id])

    @selection = Selection.create! user: @user, team:, match: @match

    respond_to do |format|
      format.js do
        @players_target = "selection-match-#{@match.id}"
        @teams_with_matches = Team.team_with_match_on(@match.day, current_section)
        @availabilities_by_user_and_match = {}
        player = @user
        @availabilities_by_user_and_match[player.id] = {}

        matches = @match.day.matches
        matches.each { |match| @availabilities_by_user_and_match[player.id][match.id] = nil }

        availabilities = MatchAvailability.includes(:user).where(match: matches, user: @user)
        availabilities.each do |availability|
          if @availabilities_by_user_and_match[availability.user_id]
            @availabilities_by_user_and_match[availability.user_id][availability.match_id] =
              availability.available
          end
        end
        @last_trainings ||= Training.of_section(current_section).with_start_between(2.months.ago,
                                                                                    6.hours.from_now).last(10)
      end
      format.html { redirect_with(fallback: section_match_path(current_section, @match)) }
      format.json { render json: {}, status: :created }
    end
  end

  def destroy
    @match = Match.find params[:id]
    @match.destroy!
    redirect_with(fallback: root_path)
  end

  def invitations
    @match = Match.find params[:id]

    MatchInvitation.create!(match: @match, user: current_user)
    redirect_to section_path(current_section), notice: 'Relance envoyée !'
  end

  protected

  def match_params
    if params[:match].present?
      params.expect(match: %i[visitor_team_id local_team_id start_datetime end_datetime
                              meeting_datetime meeting_location location_id local_score visitor_score
                              day_id championship_id])
    else
      {}
    end
  end
end

app/views/matches/_form.html.slim
= simple_form_for [current_section, @championship, @match] do |f|
  = f.error_notification

  .form-inputs
    = hidden_field_tag 'match[championship_id]', params[:match][:championship_id] if params[:match]
    div data-controller="switch-teams"
      = f.association :local_team, collection: @championship.teams.order(:name), input_html: {'data-switch-teams-target': 'team1'}
      a href='#' title='échanger les équipes' data-action="switch-teams#switch:stop"
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
        </svg>

      = f.association :visitor_team, collection: @championship.teams.order(:name), input_html: {'data-switch-teams-target': 'team2'}
    - if @match.start_datetime.present? && @match.start_datetime < Time.zone.now
      = f.input :local_score
      = f.input :visitor_score
    = f.association :location, input_html: { data: { controller: 'ts--select' }, class: 'px-0 py-0' }
    = f.association :day, collection: @championship.calendar.days.order('period_start_date ASC'), hint: "Jour de match", input_html: { data: { controller: 'ts--select' }, class: 'px-0 py-0' }
    div data-controller="linked-times"
      = f.input :start_datetime
      = f.input :meeting_datetime, hint: "Par défault, une heure avant."
    = f.input :meeting_location

  .form-actions
    = f.button :submit

app/views/matches/_match.html.slim
- match_link_url = defined?(championship) ? section_championship_match_path(current_section, championship, match) : section_match_path(current_section, match)
- match_title = "#{match.local_team&.name} - #{match.visitor_team&.name}"

li.p-1.md:p-2.block.hover:bg-gray-100.odd:bg-gray-50
  .items-center.justify-between.grid.grid-cols-1.md:grid-cols-3
    .flex.flex-col.items-center.md:items-start
      .md:mt-2.flex.items-center.text-sm.text-gray-600.sm:mt-0
        <svg class="hidden md:block mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M5.75 2a.75.75 0 01.75.75V4h7V2.75a.75.75 0 011.5 0V4h.25A2.75 2.75 0 0118 6.75v8.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25v-8.5A2.75 2.75 0 014.75 4H5V2.75A.75.75 0 015.75 2zm-1 5.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h10.5c.69 0 1.25-.56 1.25-1.25v-6.5c0-.69-.56-1.25-1.25-1.25H4.75z" clip-rule="evenodd" />
        </svg>
        p= match.date
      .div
        <p class="flex items-center text-sm text-gray-500 sm:mt-0">
          <!-- Heroicon name: mini/map-pin -->
          <svg class="hidden md:block mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M9.69 18.933l.003.001C9.89 19.02 10 19 10 19s.11.02.308-.066l.002-.001.006-.003.018-.008a5.741 5.741 0 00.281-.14c.186-.096.446-.24.757-.433.62-.384 1.445-.966 2.274-1.765C15.302 14.988 17 12.493 17 9A7 7 0 103 9c0 3.492 1.698 5.988 3.355 7.584a13.731 13.731 0 002.273 1.765 11.842 11.842 0 00.976.544l.062.029.018.008.006.003zM10 11.25a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z" clip-rule="evenodd" />
          </svg>
          = render partial: 'locations/gmaps_link', locals: { location: match.location }
        </p>
    .flex-auto
      .flex.flex-col
        .text-sm.font-semibold.font-medium.text-indigo-600.text-center
          = link_to match_title, section_day_selections_path(current_section, match.day), class: 'hover:underline text-nowrap', title: 'faire les sélections'
        - if match.local_score.present?
          .text-sm.text-center.text-indigo-500
            = "#{match.local_score} - #{match.visitor_score}"

    .flex.flex-col-reverse.items-center.md:flex-row-reverse
      - if current_user.coach_of?(current_section)
        .flex.items-center.ml-2
          = button_to invitations_section_match_path(match, section_id: current_section), title: 'Relancer les indécits',id: "match_invitations_#{match.id}", form: { data: {turbo_confirm: 'Renvoyer les mails pour les indécits ?'} }, method: :post, class: 'align-middle' do
              svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"
                path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75"
          =  button_to section_match_path(current_section, match), class: 'align-middle', :method => :delete, form: { data: {turbo_confirm: 'Supprimer ce match?'} } do
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
      .flex.flex-col
          .flex.flex-row-reverse
            - if defined?(@match_availability_counts) && @match_availability_counts
              - counts = @match_availability_counts[match.id] || {available: 0, not_available: 0, no_response: 0}
              = render partial: 'matches/presences', locals: {link_url: match_link_url, nb_presents: counts[:available], nb_not_presents: counts[:not_available], nb_no_response: counts[:no_response]}
            - else
              = render partial: 'matches/presences', locals: {link_url: match_link_url, nb_presents: match.nb_availables, nb_not_presents: match.nb_not_availables, nb_no_response: match.nb_availability_not_set}
          - user_is_player = defined?(@current_user_is_player) ? @current_user_is_player : (current_user.player_of?(current_section) && match.users.include?(current_user))
          - if user_is_player
            - availability = defined?(@current_user_availabilities) ? @current_user_availabilities[match.id]&.available : current_user.is_available_for?(match)
            .flex.flex-row-reverse.mt-2
                .flex.flex-nowrap
                  - if availability.nil?
                    = button_to 'Dispo', match_availabilities_user_path(current_user, present_ids: [match.id], checked_ids: [match.id]), method: :post, class: 'inline-flex items-center rounded-sm border border-transparent bg-indigo-100 px-1.5 py-1 text-xs font-medium text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 ml-1'
                    = button_to 'Non dispo', match_availabilities_user_path(current_user, present_ids: [match.id], checked_ids: []), method: :post, class: 'inline-flex items-center rounded-sm border border-transparent bg-indigo-100 px-1.5 py-1 text-xs font-medium text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 ml-1'
                  - elsif availability == true
                    .inline-flex.items-center.rounded-full.bg-green-100.px-2.5.py-0.5.text-xs.font-medium.text-green-800 Dispo
                    = button_to "m'indiquer non dispo", match_availabilities_user_path(current_user, present_ids: [match.id], checked_ids: []), method: :post, class: 'inline-flex items-center px-1 py-0.5 text-xs text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 underline ml-1', title: 'Change sa présence en "disponible"'
                  - else
                    .inline-flex.items-center.rounded-full.bg-red-100.px-2.5.py-0.5.text-xs.font-medium.text-red-800 Non dispo
                    = button_to "m'indiquer dispo", match_availabilities_user_path(current_user, present_ids: [match.id], checked_ids: [match.id]), method: :post, class: 'inline-flex items-center px-1 py-0.5 text-xs text-indigo-700 hover:bg-indigo-200 focus:outline-hidden focus:ring-3 focus:ring-indigo-500 focus:ring-offset-2 underline ml-1', title: 'Change sa présence en "non disponible"'

app/views/matches/_matches.html.slim
- locals = {}
- locals[:championship] = championship if defined?(championship)

.overflow-hidden.bg-white.shadow-sm.sm:rounded-md
  ul.divide-y.divide-gray-200 role="list"
    - if matches.empty?
      .p-4
        'Aucun match prévu dans les prochaines semaines
    - else
      = render partial: 'matches/match', collection: matches, locals: locals

app/views/matches/_presences.html.slim
= link_to link_url, class:'ml-2 flex flex-shrink-0 block', title:"#{nb_presents} présents / #{nb_not_presents} absents / #{nb_no_response} sans réponse" do
  p.inline-flex.rounded-full.bg-green-100.px-2.text-xs.font-semibold.leading-5.text-green-800= nb_presents
  p.inline-flex.rounded-full.bg-red-100.px-2.text-xs.font-semibold.leading-5.text-red-800= nb_not_presents
  p.inline-flex.rounded-full.bg-yellow-100.px-2.text-xs.font-semibold.leading-5.text-yellow-800= nb_no_response

app/views/matches/edit.html.slim
h1.text-xl.font-semibold.text-gray-900.text-nowrap.mb-5.mr-2
  = @match.local_team.name
  '-
  = @match.visitor_team.name

= render 'form'

app/views/matches/index.html.haml
= render partial: 'matches/matches', object: @next_matches

app/views/matches/show.html.slim
.flex
  h1.text-xl.font-semibold.text-gray-900.text-nowrap.mb-5.mr-2
    = @match.local_team.name
    '-
    = @match.visitor_team.name
  - if current_section && current_user.coach_of?(current_section)
    = link_to edit_section_championship_match_path(current_section, @match.championship, @match), title: 'Éditer le match' do
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" /></svg>

p
  = @match.date
p
  b> Score final :
  = @match.local_score
  '
  = @match.visitor_score
p
  b> Location :
  = @match.location.try(:name)
p
  b> Meeting datetime :
  = @match.meeting_datetime
p
  b> Meeting location :
  = @match.meeting_location

- if @match.day.selection_hidden?
  h2.text-xl.text-center.mt-5
    | Les sélections sont en cours de construction
- else
  - section_teams = @match.teams & current_section.teams
  .mt-5.grid.gap-5 class="grid-cols-#{section_teams.size}"
    - section_teams.each do |team|
      div
        ul.divide-y.divide-sky-600.rounded-md.border.border-sky-600
          li.bg-sky-600.p-1.text-white.text-center
            = link_to section_day_selections_path(current_section, @match.day), class: 'ml-2 text-white hover:underline', title: 'Voir les sélections' do
              = "Sélection #{team.name} (#{@match.selections(team).count} joueurs)"
              svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline ml-2"
                path stroke-linecap="round" stroke-linejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 01-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 014.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0112 15a9.065 9.065 0 00-6.23-.693L5 14.5m14.8.8l1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0112 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5"

          - @match.selections(team).each do |selection|
            li.list-group-item.px-1
              = selection.user.full_name